---@diagnostic disable
say "Hello, unyu! I'm assuming you're an unyu."
say "Did you know? I am placing helpful signs everywhere to help Unyus survive the winter."
say "I heard they need to collect those fire orbs because they're so weak and frail and dumb."
say "No offense though."
say "Anyway, did you know?"
say "You can spit liquid out by pressing X. The droplet will freeze shortly afterwards, creating a platform."
say "If you hold UP, the platform will be above you. Otherwise, it will be to the side."
say "Also, if you hold DOWN, the platform will be placed closer when placed to the side."
say "You can refill your liquid meter at a dispenser. They serve as respawn points as well."
say "If you ever get stuck, you can respawn to the last dispenser from the pause menu."
say "To open the pause menu, press the tilde/backtick/grave accent key. It's right below your ESCAPE key."
say "You can also see the controls screen on the pause menu as well."
say "If you hate arrow keys, you can change the controls to WASD from there."
say "I hope this information was useful!"
